[loggers]
keys=root

[handlers]
keys=StreamHandler

[formatters]
keys=Formatter

[logger_root]
level=DEBUG
handlers=StreamHandler

[handler_StreamHandler]
class=logging.StreamHandler
level=DEBUG
formatter=Formatter
args=(sys.stdout,)

[formatter_Formatter]
format=%(asctime)s %(levelname)s %(message)s
style=%
validate=True
class=logging.Formatter
kwargs={'secure': True}